/* =====================================================================
   PROYECTO INTEGRADOR TurismoUQ - Bases de Datos II (Universidad del Quindio)
   Entrega 1 - Script 01: DDL (tablas y restricciones)
   ===================================================================== */


/* ---------------------------------------------------------------------
   0. LIMPIEZA (permite re-ejecutar el script en el mismo esquema)
   --------------------------------------------------------------------- */
BEGIN
  FOR t IN (SELECT table_name
              FROM user_tables
             WHERE table_name IN ('ROL','USUARIO_SISTEMA','MUNICIPIO','TIPO_ALOJAMIENTO',
                                  'ALOJAMIENTO','HABITACION','TEMPORADA','TARIFA','CLIENTE',
                                  'RESERVA','RESERVA_HABITACION','PAGO','SERVICIO',
                                  'RESERVA_SERVICIO','RESENA','AUDITORIA_TARIFA'))
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

/* ---------------------------------------------------------------------
   1. CATALOGOS (no dependen de nadie)
   --------------------------------------------------------------------- */

-- ROL: perfiles de los usuarios internos de la plataforma
CREATE TABLE rol (
  id_rol       NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  nombre       VARCHAR2(40)  NOT NULL,
  descripcion  VARCHAR2(200),
  CONSTRAINT pk_rol        PRIMARY KEY (id_rol),
  CONSTRAINT uk_rol_nombre UNIQUE (nombre)
);
COMMENT ON TABLE rol IS 'Roles de los usuarios internos (administrador de plataforma, encargado de alojamiento, etc.).';

-- MUNICIPIO: los 12 municipios del Quindio
CREATE TABLE municipio (
  id_municipio  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(60)  NOT NULL,
  CONSTRAINT pk_municipio        PRIMARY KEY (id_municipio),
  CONSTRAINT uk_municipio_nombre UNIQUE (nombre)
);
COMMENT ON TABLE municipio IS 'Municipios del departamento donde hay oferta de alojamiento.';

-- TIPO_ALOJAMIENTO: finca cafetera, hotel, glamping, hostal, etc.
CREATE TABLE tipo_alojamiento (
  id_tipo_alojamiento  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  nombre               VARCHAR2(40)  NOT NULL,
  descripcion          VARCHAR2(200),
  CONSTRAINT pk_tipo_alojamiento        PRIMARY KEY (id_tipo_alojamiento),
  CONSTRAINT uk_tipo_alojamiento_nombre UNIQUE (nombre)
);
COMMENT ON TABLE tipo_alojamiento IS 'Catalogo de tipos de alojamiento (finca cafetera, hotel, glamping, hostal...).';

-- TEMPORADA: rangos de fechas por anio con su categoria (alta/media/baja)
CREATE TABLE temporada (
  id_temporada  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  nombre        VARCHAR2(60)  NOT NULL,
  categoria     VARCHAR2(5)   NOT NULL,
  anio          NUMBER(4)     NOT NULL,
  fecha_inicio  DATE          NOT NULL,
  fecha_fin     DATE          NOT NULL,
  CONSTRAINT pk_temporada        PRIMARY KEY (id_temporada),
  CONSTRAINT uk_temporada_nombre UNIQUE (nombre, anio),
  CONSTRAINT ck_temporada_categoria CHECK (categoria IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT ck_temporada_anio      CHECK (anio = EXTRACT(YEAR FROM fecha_inicio)),
  CONSTRAINT ck_temporada_fechas    CHECK (fecha_fin >= fecha_inicio)
);
COMMENT ON TABLE temporada IS 'Temporadas del departamento por anio (Semana Santa 2025 y 2026 son filas distintas). anio = anio de fecha_inicio; fecha_fin es inclusiva. Deben cubrir 2024-2026 sin solapes ni huecos.';

-- CLIENTE: personas que reservan
CREATE TABLE cliente (
  id_cliente      NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  tipo_documento  VARCHAR2(3)   NOT NULL,
  num_documento   VARCHAR2(20)  NOT NULL,
  nombres         VARCHAR2(80)  NOT NULL,
  apellidos       VARCHAR2(80)  NOT NULL,
  correo          VARCHAR2(120) NOT NULL,
  telefono        VARCHAR2(20),
  ciudad_origen   VARCHAR2(80)  NOT NULL,
  CONSTRAINT pk_cliente           PRIMARY KEY (id_cliente),
  CONSTRAINT uk_cliente_documento UNIQUE (tipo_documento, num_documento),
  CONSTRAINT uk_cliente_correo    UNIQUE (correo),
  CONSTRAINT ck_cliente_tipodoc   CHECK (tipo_documento IN ('CC','CE','PAS')),
  CONSTRAINT ck_cliente_correo    CHECK (correo LIKE '%_@_%.%')
);
COMMENT ON TABLE cliente IS 'Clientes registrados en la plataforma; ciudad_origen no se limita al Quindio.';


/* ---------------------------------------------------------------------
   2. OFERTA DE ALOJAMIENTO
   --------------------------------------------------------------------- */

-- ALOJAMIENTO: cada establecimiento, de un municipio y un tipo
CREATE TABLE alojamiento (
  id_alojamiento       NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_municipio         NUMBER(10)    NOT NULL,
  id_tipo_alojamiento  NUMBER(10)    NOT NULL,
  nombre_comercial     VARCHAR2(120) NOT NULL,
  direccion            VARCHAR2(200) NOT NULL,
  estrellas            NUMBER(1)     NOT NULL, 
  telefono             VARCHAR2(20),
  correo               VARCHAR2(120) NOT NULL,
  CONSTRAINT pk_alojamiento        PRIMARY KEY (id_alojamiento),
  CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio)
             REFERENCES municipio (id_municipio),
  CONSTRAINT fk_alojamiento_tipo      FOREIGN KEY (id_tipo_alojamiento)
             REFERENCES tipo_alojamiento (id_tipo_alojamiento),
  CONSTRAINT uk_alojamiento_nombre    UNIQUE (id_municipio, nombre_comercial),
  CONSTRAINT uk_alojamiento_correo    UNIQUE (correo),
  CONSTRAINT ck_alojamiento_estrellas CHECK (estrellas BETWEEN 1 AND 5),
  CONSTRAINT ck_alojamiento_correo    CHECK (correo LIKE '%_@_%.%')
);
COMMENT ON TABLE alojamiento IS 'Establecimientos de hospedaje. La calificacion en estrellas es autoasignada, no es la de las resenas.';

-- HABITACION: unidades reservables de cada alojamiento
CREATE TABLE habitacion (
  id_habitacion    NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento   NUMBER(10)    NOT NULL,
  numero           VARCHAR2(10)  NOT NULL,
  capacidad_max    NUMBER(2)     NOT NULL,
  tipo_habitacion  VARCHAR2(10)  NOT NULL,
  descripcion      VARCHAR2(300),
  CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uk_habitacion_numero UNIQUE (id_alojamiento, numero),
  CONSTRAINT uk_habitacion_id_aloj UNIQUE (id_habitacion, id_alojamiento),
  CONSTRAINT ck_habitacion_capacidad CHECK (capacidad_max BETWEEN 1 AND 20),
  CONSTRAINT ck_habitacion_tipo      CHECK (tipo_habitacion IN ('SENCILLA','DOBLE','SUITE','CABANA'))
);
COMMENT ON TABLE habitacion IS 'Habitaciones de cada alojamiento; dos habitaciones del mismo alojamiento no comparten numero.';

-- TARIFA: precio por noche de cada habitacion en cada temporada 
CREATE TABLE tarifa (
  id_habitacion  NUMBER(10)    NOT NULL,
  id_temporada   NUMBER(10)    NOT NULL,
  precio_noche   NUMBER(10,2)  NOT NULL,
  CONSTRAINT pk_tarifa PRIMARY KEY (id_habitacion, id_temporada),
  CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion)
             REFERENCES habitacion (id_habitacion),
  CONSTRAINT fk_tarifa_temporada  FOREIGN KEY (id_temporada)
             REFERENCES temporada (id_temporada),
  CONSTRAINT ck_tarifa_precio CHECK (precio_noche > 0)
);
COMMENT ON TABLE tarifa IS 'Precio por noche de una habitacion en una temporada. Una estadia que cruza temporadas se valora noche por noche con estas filas.';

-- SERVICIO: servicios complementarios, propios de cada alojamiento
CREATE TABLE servicio (
  id_servicio     NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento  NUMBER(10)    NOT NULL,
  nombre          VARCHAR2(80)  NOT NULL,
  descripcion     VARCHAR2(300),
  precio          NUMBER(10,2)  NOT NULL,
  CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uk_servicio_nombre UNIQUE (id_alojamiento, nombre),
  CONSTRAINT uk_servicio_id_aloj UNIQUE (id_servicio, id_alojamiento),
  CONSTRAINT ck_servicio_precio CHECK (precio >= 0)
);
COMMENT ON TABLE servicio IS 'Servicios complementarios; el desayuno del Hotel X y el del Hotel Y son servicios distintos.';


/* ---------------------------------------------------------------------
   3. RESERVAS, PAGOS Y RESENAS
   --------------------------------------------------------------------- */

-- RESERVA: cabecera de la reserva (un cliente, un alojamiento, rango general)
CREATE TABLE reserva (
  id_reserva         NUMBER(10)   GENERATED BY DEFAULT AS IDENTITY,
  id_cliente         NUMBER(10)   NOT NULL,
  id_alojamiento     NUMBER(10)   NOT NULL,
  fecha_creacion     DATE         DEFAULT SYSDATE NOT NULL,
  fecha_checkin      DATE         NOT NULL,
  fecha_checkout     DATE         NOT NULL,
  estado             VARCHAR2(10) DEFAULT 'PENDIENTE' NOT NULL,
  fecha_cancelacion  DATE,     
  CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
  CONSTRAINT fk_reserva_cliente    FOREIGN KEY (id_cliente)
             REFERENCES cliente (id_cliente),
  CONSTRAINT fk_reserva_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uk_reserva_id_aloj UNIQUE (id_reserva, id_alojamiento),
  CONSTRAINT ck_reserva_estado CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
  CONSTRAINT ck_reserva_fechas CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reserva_creacion CHECK (TRUNC(fecha_creacion) <= fecha_checkin),
  CONSTRAINT ck_reserva_cancelacion CHECK (
        (estado = 'CANCELADA'  AND fecha_cancelacion IS NOT NULL
                               AND TRUNC(fecha_cancelacion) <= fecha_checkin)
     OR (estado <> 'CANCELADA' AND fecha_cancelacion IS NULL))
);
COMMENT ON TABLE reserva IS 'Cabecera de reserva: un cliente, un alojamiento y un rango general de fechas; las habitaciones van en RESERVA_HABITACION.';

-- RESERVA_HABITACION: lineas de la reserva (una por habitacion)
CREATE TABLE reserva_habitacion (
  id_reserva_habitacion  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_reserva             NUMBER(10)    NOT NULL,
  id_habitacion          NUMBER(10)    NOT NULL,
  id_alojamiento         NUMBER(10)    NOT NULL,  
  fecha_checkin          DATE          NOT NULL,
  fecha_checkout         DATE          NOT NULL,
  num_huespedes          NUMBER(2)     NOT NULL,
  valor_estadia          NUMBER(12,2)  NOT NULL,  
  CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva_habitacion),
  CONSTRAINT fk_reshab_reserva    FOREIGN KEY (id_reserva, id_alojamiento)
             REFERENCES reserva (id_reserva, id_alojamiento),
  CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion, id_alojamiento)
             REFERENCES habitacion (id_habitacion, id_alojamiento),
  CONSTRAINT uk_reshab_linea UNIQUE (id_reserva, id_habitacion),
  CONSTRAINT ck_reshab_fechas    CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reshab_huespedes CHECK (num_huespedes >= 1),
  CONSTRAINT ck_reshab_valor     CHECK (valor_estadia >= 0)
);
COMMENT ON TABLE reserva_habitacion IS 'Linea de reserva: habitacion, fechas propias dentro del rango de la reserva, huespedes y valor de la estadia. Lleva id_alojamiento para amarrar reserva y habitacion al mismo alojamiento. La ocupacion se calcula con estas fechas.';

-- PAGO: abonos de una reserva
CREATE TABLE pago (
  id_pago     NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_reserva  NUMBER(10)    NOT NULL,
  fecha_pago  DATE          DEFAULT SYSDATE NOT NULL,
  monto       NUMBER(12,2)  NOT NULL,
  metodo      VARCHAR2(20)  NOT NULL,
  estado      VARCHAR2(12)  NOT NULL,
  monto_reembolsado  NUMBER(12,2),  
  CONSTRAINT pk_pago PRIMARY KEY (id_pago),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva)
             REFERENCES reserva (id_reserva),
  CONSTRAINT ck_pago_monto  CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
  CONSTRAINT ck_pago_reembolso CHECK (
        (estado = 'REEMBOLSADO'  AND monto_reembolsado > 0 AND monto_reembolsado <= monto)
     OR (estado <> 'REEMBOLSADO' AND monto_reembolsado IS NULL))
);
COMMENT ON TABLE pago IS 'Pagos/abonos de una reserva. Se considera pagada cuando la suma de pagos EXITOSOS cubre estadia + servicios. monto_reembolsado guarda lo devuelto en los pagos REEMBOLSADOS.';

-- RESERVA_SERVICIO: servicios contratados dentro de una reserva
CREATE TABLE reserva_servicio (
  id_reserva_servicio  NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_reserva           NUMBER(10)    NOT NULL,
  id_servicio          NUMBER(10)    NOT NULL,
  id_alojamiento       NUMBER(10)    NOT NULL,  
  cantidad             NUMBER(3)     NOT NULL,
  precio_unitario      NUMBER(10,2)  NOT NULL,  
  CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
  CONSTRAINT fk_ressrv_reserva  FOREIGN KEY (id_reserva, id_alojamiento)
             REFERENCES reserva (id_reserva, id_alojamiento),
  CONSTRAINT fk_ressrv_servicio FOREIGN KEY (id_servicio, id_alojamiento)
             REFERENCES servicio (id_servicio, id_alojamiento),
  CONSTRAINT uk_ressrv_linea    UNIQUE (id_reserva, id_servicio),
  CONSTRAINT ck_ressrv_cantidad CHECK (cantidad >= 1),
  CONSTRAINT ck_ressrv_precio   CHECK (precio_unitario >= 0)
);
COMMENT ON TABLE reserva_servicio IS 'Servicios contratados en una reserva: cada servicio una vez por reserva, con varias unidades en cantidad. Lleva id_alojamiento para amarrar reserva y servicio al mismo alojamiento.';

-- RESENA: una resena por reserva completada
CREATE TABLE resena (
  id_resena     NUMBER(10)     GENERATED BY DEFAULT AS IDENTITY,
  id_reserva    NUMBER(10)     NOT NULL,
  calificacion  NUMBER(1)      NOT NULL,
  comentario    VARCHAR2(1000),
  fecha_resena  DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_resena PRIMARY KEY (id_resena),
  CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva)
             REFERENCES reserva (id_reserva),
  CONSTRAINT uk_resena_reserva UNIQUE (id_reserva),
  CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);
COMMENT ON TABLE resena IS 'Resena del alojamiento ligada a una reserva COMPLETADA (maximo una por reserva). El alojamiento se obtiene por RESERVA.id_alojamiento.';


/* ---------------------------------------------------------------------
   4. USUARIOS INTERNOS
   --------------------------------------------------------------------- */

-- USUARIO_SISTEMA: administradores y encargados de alojamiento
CREATE TABLE usuario_sistema (
  id_usuario       NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  id_rol           NUMBER(10)    NOT NULL,
  id_alojamiento   NUMBER(10),              
  username         VARCHAR2(40)  NOT NULL,
  nombre_completo  VARCHAR2(120) NOT NULL,
  correo           VARCHAR2(120) NOT NULL,
  estado           VARCHAR2(10)  DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
  CONSTRAINT fk_usuario_rol         FOREIGN KEY (id_rol)
             REFERENCES rol (id_rol),
  CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento)
             REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uk_usuario_username UNIQUE (username),
  CONSTRAINT uk_usuario_correo   UNIQUE (correo),
  CONSTRAINT ck_usuario_estado   CHECK (estado IN ('ACTIVO','INACTIVO')),
  CONSTRAINT ck_usuario_correo   CHECK (correo LIKE '%_@_%.%')
);
COMMENT ON TABLE usuario_sistema IS 'Usuarios internos: administradores de plataforma y encargados (ligados a un alojamiento). Base para los roles de la Entrega 3.';


/* ---------------------------------------------------------------------
   5. BITACORA
   --------------------------------------------------------------------- */

-- AUDITORIA_TARIFA: historial de cambios sobre TARIFA 
CREATE TABLE auditoria_tarifa (
  id_auditoria     NUMBER(10)    GENERATED BY DEFAULT AS IDENTITY,
  usuario          VARCHAR2(128) DEFAULT USER NOT NULL, 
  fecha            DATE          DEFAULT SYSDATE NOT NULL,
  operacion        VARCHAR2(6)   NOT NULL,
  id_habitacion    NUMBER(10)    NOT NULL,
  id_temporada     NUMBER(10)    NOT NULL,
  precio_anterior  NUMBER(10,2),                          
  precio_nuevo     NUMBER(10,2),                        
  CONSTRAINT pk_auditoria_tarifa PRIMARY KEY (id_auditoria),
  CONSTRAINT ck_audtar_operacion CHECK (operacion IN ('INSERT','UPDATE','DELETE')),
  CONSTRAINT ck_audtar_precios CHECK (
        (operacion = 'INSERT' AND precio_anterior IS NULL     AND precio_nuevo IS NOT NULL)
     OR (operacion = 'UPDATE' AND precio_anterior IS NOT NULL AND precio_nuevo IS NOT NULL)
     OR (operacion = 'DELETE' AND precio_anterior IS NOT NULL AND precio_nuevo IS NULL))
);
COMMENT ON TABLE auditoria_tarifa IS 'Bitacora de cambios de TARIFA (quien, cuando, precio anterior y nuevo). Sin FK para conservar el historial.';


/* ---------------------------------------------------------------------
   6. VERIFICACION (resultado esperado: 16 tablas)
   --------------------------------------------------------------------- */
SELECT table_name FROM user_tables ORDER BY table_name;

-- Restricciones por tabla: P = PK, R = FK, U = UNIQUE, C = CHECK / NOT NULL
SELECT table_name,
       SUM(CASE WHEN constraint_type = 'P' THEN 1 ELSE 0 END) AS pk,
       SUM(CASE WHEN constraint_type = 'R' THEN 1 ELSE 0 END) AS fk,
       SUM(CASE WHEN constraint_type = 'U' THEN 1 ELSE 0 END) AS uk,
       SUM(CASE WHEN constraint_type = 'C' THEN 1 ELSE 0 END) AS ck_y_not_null
  FROM user_constraints
 GROUP BY table_name
 ORDER BY table_name;
